services:
  db:
    image: mariadb:10.6.22
    container_name: chickencare-db
    environment:
      MYSQL_DATABASE: chickencare
      MYSQL_USER: chickencare
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - chickencare_db_data:/var/lib/mysql

volumes:
  chickencare_db_data:
